from flask import Flask, render_template, Response
import cv2
import mediapipe as mp

app = Flask(__name__)

# Initialize MediaPipe Hand Landmarks and Face Detection models
mp_hands = mp.solutions.hands
mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

hands = mp_hands.Hands()
face_detection = mp_face_detection.FaceDetection()

# Initialize webcam feed
camera = cv2.VideoCapture(0)

@app.route('/')
def index():
    # Render the homepage
    return render_template('index.html')

def generate_frames():
    while True:
        # Capture frame from the webcam
        success, frame = camera.read()
        if not success:
            break
        else:
            # Convert the BGR image to RGB for MediaPipe processing
            image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            # Process the image for hand landmarks
            hand_results = hands.process(image)

            # Process the image for face detection
            face_results = face_detection.process(image)

            # Convert the image back to BGR for OpenCV
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

            # Draw hand landmarks if detected
            if hand_results.multi_hand_landmarks:
                for hand_landmarks in hand_results.multi_hand_landmarks:
                    mp_drawing.draw_landmarks(image, hand_landmarks, mp_hands.HAND_CONNECTIONS)

            # Draw face detection box if detected
            if face_results.detections:
                for detection in face_results.detections:
                    mp_drawing.draw_detection(image, detection)

            # Encode the frame to be sent to the client
            ret, buffer = cv2.imencode('.jpg', image)
            frame = buffer.tobytes()

            # Yield the frame in byte format
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/video_feed')
def video_feed():
    # Return the response generated by the video feed
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(debug=True)
